#include <iostream>
#include <exception>
#include "queue.hpp"

/*void test_empty_buffer()
{
	CircularQueue Q(6);
	try {
		Q.dequeue();
		std::cout << "TEST test_empty_buffer: FAILED" << std::endl;	
	}
       	catch (...) {
		std::cout << "TEST test_empty_buffer: PASSED" << std::endl;
	}
}

void test_buffer_read()
{
	int size = 7;
	CircularQueue Q(size);
	for(int i = 0; i < 100; i++) {
		Q.enqueue(2 * i);
	}
	for(int i = 0; i < 100; i++) {
		if (2 * i != Q.dequeue()) {
			std::cout << "TEST test_buffer_read: FAILED" << std::endl;
			break;
		}
	}	
	std::cout << "TEST test_buffer_read: PASSED" << std::endl;
}
*/
int main() {
//	test_empty_buffer();
//	test_buffer_read();
//	test_buffer_write();
//	test_buffer_peak();
//	test_full_buffer();
	return 0;
}
